version: "{branch}-{build}"

platform: x64

branches:
  only:
    - go-rewrite

# Source Config
clone_folder: c:\gopath\src\magnetico
shallow_clone: true

# Build host
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9.2
  DEPVERSION: 0.3.2

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin
  - go version
  - go env
  - appveyor DownloadFile https://github.com/golang/dep/releases/download/v%DEPVERSION%/dep-windows-amd64 -FileName c:\go\bin\dep
  - go get -u github.com/jteeuwen/go-bindata/...

before_build:
  - go-bindata -o="magneticow/bindata.go" -prefix="magneticow/data/" magneticow/data/...
  - cd c:\gopath\src\magnetico
  - dep ensure -v

build_script:
  - go install magnetico/magneticod
  - go install magnetico/magneticow

test_script:
  - go test -cover magnetico/magneticod/...
  - go test -cover magnetico/magneticow/...
  - go test -cover magnetico/persistence/...
